const db = require('../config/db');

/**
 * Create a notification in the database
 * @param {number} userId - Receiver's user ID
 * @param {string} title - Notification title
 * @param {string} message - Notification message
 * @param {string} type - Notification type (return, request, invoice, document, etc.)
 * @param {string} referenceType - Reference type (returns, document_request, invoices, etc.)
 * @param {number} referenceId - ID of the referenced entity
 * @returns {Promise} - Promise resolving to the insert result
 */
const createNotification = (userId, title, message, type, referenceType = null, referenceId = null) => {
    return new Promise((resolve, reject) => {
        const query = `
      INSERT INTO notifications (user_id, title, message, type, reference_type, reference_id, created_at)
      VALUES (?, ?, ?, ?, ?, ?, NOW())
    `;

        db.query(query, [userId, title, message, type, referenceType, referenceId], (err, result) => {
            if (err) {
                console.error('Error creating notification:', err);
                reject(err);
            } else {
                console.log(`✅ Notification created for user ${userId}: ${title}`);
                resolve(result);
            }
        });
    });
};

/**
 * Notify CA about a new document request from client
 * @param {number} caUserId - CA's user ID
 * @param {string} clientName - Client's business name
 * @param {string} requestType - Type of request
 * @param {number} requestId - Request ID
 */
const notifyNewDocumentRequest = async (caUserId, clientName, requestType, requestId) => {
    const title = 'New Document Request';
    const message = `${clientName} has submitted a ${requestType}`;
    return createNotification(caUserId, title, message, 'request', 'document_request', requestId);
};

/**
 * Notify client about a new return created by CA
 * @param {number} clientUserId - Client's user ID
 * @param {string} returnType - Type of return
 * @param {string} financialYear - Financial year
 * @param {number} returnId - Return ID
 */
const notifyReturnCreated = async (clientUserId, returnType, financialYear, returnId) => {
    const title = 'New Return Created';
    const message = `A ${returnType} for ${financialYear} has been created`;
    return createNotification(clientUserId, title, message, 'return', 'returns', returnId);
};

/**
 * Notify client about a new invoice generated by CA
 * @param {number} clientUserId - Client's user ID
 * @param {string} invoiceNumber - Invoice number (not used in message)
 * @param {number} amount - Invoice amount
 * @param {number} invoiceId - Invoice ID
 */
const notifyInvoiceGenerated = async (clientUserId, invoiceNumber, amount, invoiceId) => {
    const title = 'New Invoice Generated';
    const message = `A new invoice for ₹${amount.toLocaleString('en-IN')} has been generated`;
    return createNotification(clientUserId, title, message, 'invoice', 'invoices', invoiceId);
};

/**
 * Notify client that CA has replied to their request
 * @param {number} clientUserId - Client's user ID
 * @param {string} requestType - Type of request
 * @param {number} requestId - Request ID
 */
const notifyRequestReplied = async (clientUserId, requestType, requestId) => {
    const title = 'CA Replied to Your Request';
    const message = `Your CA has responded to your ${requestType}`;
    return createNotification(clientUserId, title, message, 'reply', 'document_request', requestId);
};

/**
 * Notify client about a new document uploaded by CA
 * @param {number} clientUserId - Client's user ID
 * @param {string} documentName - Document name
 * @param {string} categoryName - Document category
 * @param {number} documentId - Document ID
 */
const notifyDocumentUploaded = async (clientUserId, documentName, categoryName, documentId) => {
    const title = 'New Document Uploaded';
    const message = `${documentName} (${categoryName}) has been uploaded`;
    return createNotification(clientUserId, title, message, 'document', 'documents', documentId);
};

module.exports = {
    createNotification,
    notifyNewDocumentRequest,
    notifyReturnCreated,
    notifyInvoiceGenerated,
    notifyRequestReplied,
    notifyDocumentUploaded
};
